### PR TITLE
Added api design to README

### PR DESCRIPTION
**Pull request by jedster1111**
I'm not a hundred percent sure if this is what you were looking for.

### CODE REVIEW

**Comment by roybailey** [comment]
API document needs to contain enough for someone to program a client.  So including json payload examples for requests and responses.  e.g. Showing the sequence of calls to this API that allows a client to create, vote and see results of a poll.

**Comment by roybailey** [comment]
#### Use the multi-line code blocks to show json payloads e.g.

```
{
  "id": "0123456789",
  "title": "Visitor Entertainment Venue",
  "description": "Poll to find out preferred venue for taking our USA guests for evening out next week",
  "options": [
    "Bowling",
    "Skydiving",
    "Rock Climbing"
  ]
}
```

> You can use `https://jsoneditoronline.org/` to help validate and format your json samples

#### Include status return codes for 200 and 400 with different payloads

http status 200 : for value response payload
http status 400 : for bad request with error in request payload

> You can use `https://httpstatuses.com/` to review appropriate codes

**Comment by jedster1111** [comment]
At the moment there's no concept of checking whether the voter has already voted or not.
Possibly one solution is to use email addresses to check for uniqueness of votes. This would solve the problem of having two people in the office with the same name causing conflicts. We could then keep track of votes server side and allow each email a certain number of votes.
I'll add the error response to the vote endpoint though.

**Comment by roybailey** [comment]
* Remove response payload from delete action
* Use `somethingId` naming for identifiers
* Add use-case description to each API call e.g. `Create a new Poll` for the `POST /polls` api call
* extract typo of text inside json code block

**Comment by roybailey** [comment]
👍

**Pull request merged**
